name: docker

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Docker image tag
        default: latest
  push:
    paths:
      - .github/workflows/docker.yaml
      - Dockerfile
      - environment.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Free up disk space
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
  
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push notebook
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          file: Dockerfile
          tags: iamzoltan/climatematch-notebook:${{ github.event.inputs.tag || 'latest' }}
